version: '3.9'

services:
  django:
    image: django-docker:0.0.1
    build: 
    ports:
      - "8000:8000"

  mysql:
    build: ./mysql/
    restart : always
    environment:
      MYSQL_DATABASE : "pet-adoption"
      MYSQL_ROOT_PASSWORD : "root"
    ports:
      - "3306:3306"

